apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-extractor-backend
  labels:
    app: pdf-extractor-backend
spec:
  replicas: 3 # Manual Scaling: Adjust this value to scale manually, or use 'kubectl scale deployment/pdf-extractor-backend --replicas=5'
  selector:
    matchLabels:
      app: pdf-extractor-backend
  revisionHistoryLimit: 5 # Keeps the last 5 ReplicaSets for easy rollbacks
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # maxSurge: 1 means K8s will create 1 new pod before killing an old one (4 pods total during update)
      maxSurge: 1 
      # maxUnavailable: 1 means K8s will kill at most 1 pod while creating new ones (2 pods minimum during update)
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: pdf-extractor-backend
    spec:
      containers:
        - name: backend
          image: pdf-extractor-backend:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: pdf-extractor-config
                  key: APP_ENV
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: pdf-extractor-config
                  key: APP_VERSION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pdf-extractor-secrets
                  key: DB_PASSWORD
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: pdf-extractor-secrets
                  key: API_KEY
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          # Resource management is critical for cluster stability.
          # Requests: Used by the scheduler to find a suitable node.
          # Limits: Hard cap to prevent a single pod from starving others (Noisy Neighbor).
          resources:
            requests:
              # FastAPI + PyPDF2 needs a baseline to start and handle initial requests.
              # 250m ensures the pod isn't scheduled on an over-committed node.
              cpu: "250m"
              # 256Mi is sufficient for the Python runtime and processing moderately sized PDFs.
              memory: "256Mi"
            limits:
              # Limit CPU to 1 core to prevent a complex PDF extraction from consuming all node CPU.
              cpu: "1000m"
              # 512Mi limit prevents OOM (Out Of Memory) issues from crashing the node if a massive PDF is uploaded.
              memory: "512Mi"

